package: buchungskalender
version: 1.1.0
author: Wolfgang Bund
supportpage: https://github.com/redaxo/redaxo

page:
    title: 'Buchungskalender'
    perm: buchungskalender
    pjax: true
    icon: rex-icon fa-calendar
    subpages:
        overview:
            title: 'translate:buchungskalender_overview'
        calendar:
            title: 'translate:buchungskalender_calendar'
        bookings:
            title: 'translate:buchungskalender_bookings'
        settings:
            title: 'translate:buchungskalender_subpage_config'
            perm: admin[]
        setup:
            title: 'translate:buchungskalender_subpage_setup'
            perm: admin[]
        help:  
            title: 'translate:buchungskalender_help'
            icon: rex-icon fa-question-circle
            itemclass: pull-right
            subPath: README.md

pages:
    bukabookingsprint:
        title: translate:bookings_print
        main: true
#        block: system
        popup: true
        hidden: true
        perm: buchungskalender_print[]
#        pjax: true


requires:
    php:
        version: '>=7.3'
    redaxo: ">=5.8.0"
    packages:
        yform: '>=3.2'
